name: Android CI

on: [push]

jobs:

  android-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - uses: actions/checkout@v2
      - name: Decrypt large secret
          run: ./.github/scripts/decrypt_secret.sh
          env:
            MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
              # This command is just an example to show your secret being printed
              # Ensure you remove any print statements of your secrets. GitHub does
            # not hide secrets that use this workaround.
      - name: Test printing your secret (Remove this step in production)
          run: cat $HOME/secrets/mapbox_token.json

      - name: "Android CI Github Action"
        uses: code0987/android-ci-github-action@master
        env:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
        with:
          MAPBOX_DOWNLOADS_TOKEN: ${{ secrets.MAPBOX_DOWNLOADS_TOKEN }}
          args: |
            npm install
            export GRADLE_USER_HOME=`pwd`./src/.gradle
            chmod 755 ./src/gradlew
            ./gradlew -p ./src check
            ./gradlew assembleDebug
      - name: ls
        run: ls

      - name: Archive production artifacts
        uses: actions/upload-artifact@master
        with:
          path: app/build/outputs/apk/debug/*.apk