name: Android CI

on: [push]

jobs:

  android-ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: "Android CI Github Action"
        uses: code0987/android-ci-github-action@master
        with:
          args: |
            npm install
            export GRADLE_USER_HOME=`pwd`./src/.gradle
            chmod 755 ./src/gradlew
            ./gradlew -p ./src check
            ./gradlew assembleDebug

      - name: ls
        run: ls

#      - name: Archive production artifacts
#        uses: actions/upload-artifact@master
#        with:
#          name: compiled
#            path: para-flight/app/build/outputs/apk/debug/para-flight-1.0.1-debug.apk